{% set name = "napari-deepmeta" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-deepmeta-{{ version }}.tar.gz
  sha256: dab7a521af490d865ee8aff82f41e7ec4016d43b8b3e65247cad65e401f7f0e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - connected-components-3d
    - napari ==0.4.8
    - napari-plugin-engine >=0.1.4
    - numpy
    - opencv
    - pyqt
    - pytest
    - pytest-cov
    - pytest-qt
    - pytest-xvfb
    - python >={{ python_min }}
    - qtpy >=1.9.0
    - scikit-image
    - tensorflow

test:
  imports:
    - deepmeta
  commands:
    - pip list
    # - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/EdgarLefevre/napari-deepmeta
  summary: Segment mouse lungs and metastasis on MRI images.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
